# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  userprojectapi:
    image: userprojectapi
    build:
      context: .
      dockerfile: src/UserProject.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5252:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
